server:
  port: 7788
  
spring:
  application:    name: user2  data:    mongodb:      uri: mongodb://localhost:27017/mongodb
      
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

      