package com.ysc.mapper;

import com.ysc.entity.PeopleFlow;
import com.ysc.entity.PeopleFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PeopleFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_flow
     *
     * @mbg.generated Mon Apr 15 11:15:08 CST 2019
     */
    long countByExample(PeopleFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_flow
     *
     * @mbg.generated Mon Apr 15 11:15:08 CST 2019
     */
    int deleteByExample(PeopleFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_flow
     *
     * @mbg.generated Mon Apr 15 11:15:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_flow
     *
     * @mbg.generated Mon Apr 15 11:15:08 CST 2019
     */
    int insert(PeopleFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_flow
     *
     * @mbg.generated Mon Apr 15 11:15:08 CST 2019
     */
    int insertSelective(PeopleFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_flow
     *
     * @mbg.generated Mon Apr 15 11:15:08 CST 2019
     */
    List<PeopleFlow> selectByExample(PeopleFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_flow
     *
     * @mbg.generated Mon Apr 15 11:15:08 CST 2019
     */
    PeopleFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_flow
     *
     * @mbg.generated Mon Apr 15 11:15:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") PeopleFlow record, @Param("example") PeopleFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_flow
     *
     * @mbg.generated Mon Apr 15 11:15:08 CST 2019
     */
    int updateByExample(@Param("record") PeopleFlow record, @Param("example") PeopleFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_flow
     *
     * @mbg.generated Mon Apr 15 11:15:08 CST 2019
     */
    int updateByPrimaryKeySelective(PeopleFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_flow
     *
     * @mbg.generated Mon Apr 15 11:15:08 CST 2019
     */
    int updateByPrimaryKey(PeopleFlow record);
}