package com.ysc.entity;

import java.util.ArrayList;
import java.util.List;

public class SchedulejobExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    public SchedulejobExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJobidIsNull() {
            addCriterion("jobId is null");
            return (Criteria) this;
        }

        public Criteria andJobidIsNotNull() {
            addCriterion("jobId is not null");
            return (Criteria) this;
        }

        public Criteria andJobidEqualTo(Integer value) {
            addCriterion("jobId =", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidNotEqualTo(Integer value) {
            addCriterion("jobId <>", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidGreaterThan(Integer value) {
            addCriterion("jobId >", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidGreaterThanOrEqualTo(Integer value) {
            addCriterion("jobId >=", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidLessThan(Integer value) {
            addCriterion("jobId <", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidLessThanOrEqualTo(Integer value) {
            addCriterion("jobId <=", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidIn(List<Integer> values) {
            addCriterion("jobId in", values, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidNotIn(List<Integer> values) {
            addCriterion("jobId not in", values, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidBetween(Integer value1, Integer value2) {
            addCriterion("jobId between", value1, value2, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidNotBetween(Integer value1, Integer value2) {
            addCriterion("jobId not between", value1, value2, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobnameIsNull() {
            addCriterion("jobName is null");
            return (Criteria) this;
        }

        public Criteria andJobnameIsNotNull() {
            addCriterion("jobName is not null");
            return (Criteria) this;
        }

        public Criteria andJobnameEqualTo(String value) {
            addCriterion("jobName =", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotEqualTo(String value) {
            addCriterion("jobName <>", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameGreaterThan(String value) {
            addCriterion("jobName >", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameGreaterThanOrEqualTo(String value) {
            addCriterion("jobName >=", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameLessThan(String value) {
            addCriterion("jobName <", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameLessThanOrEqualTo(String value) {
            addCriterion("jobName <=", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameLike(String value) {
            addCriterion("jobName like", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotLike(String value) {
            addCriterion("jobName not like", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameIn(List<String> values) {
            addCriterion("jobName in", values, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotIn(List<String> values) {
            addCriterion("jobName not in", values, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameBetween(String value1, String value2) {
            addCriterion("jobName between", value1, value2, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotBetween(String value1, String value2) {
            addCriterion("jobName not between", value1, value2, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobgroupIsNull() {
            addCriterion("jobGroup is null");
            return (Criteria) this;
        }

        public Criteria andJobgroupIsNotNull() {
            addCriterion("jobGroup is not null");
            return (Criteria) this;
        }

        public Criteria andJobgroupEqualTo(String value) {
            addCriterion("jobGroup =", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupNotEqualTo(String value) {
            addCriterion("jobGroup <>", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupGreaterThan(String value) {
            addCriterion("jobGroup >", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupGreaterThanOrEqualTo(String value) {
            addCriterion("jobGroup >=", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupLessThan(String value) {
            addCriterion("jobGroup <", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupLessThanOrEqualTo(String value) {
            addCriterion("jobGroup <=", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupLike(String value) {
            addCriterion("jobGroup like", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupNotLike(String value) {
            addCriterion("jobGroup not like", value, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupIn(List<String> values) {
            addCriterion("jobGroup in", values, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupNotIn(List<String> values) {
            addCriterion("jobGroup not in", values, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupBetween(String value1, String value2) {
            addCriterion("jobGroup between", value1, value2, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andJobgroupNotBetween(String value1, String value2) {
            addCriterion("jobGroup not between", value1, value2, "jobgroup");
            return (Criteria) this;
        }

        public Criteria andCronexpressionIsNull() {
            addCriterion("cronExpression is null");
            return (Criteria) this;
        }

        public Criteria andCronexpressionIsNotNull() {
            addCriterion("cronExpression is not null");
            return (Criteria) this;
        }

        public Criteria andCronexpressionEqualTo(String value) {
            addCriterion("cronExpression =", value, "cronexpression");
            return (Criteria) this;
        }

        public Criteria andCronexpressionNotEqualTo(String value) {
            addCriterion("cronExpression <>", value, "cronexpression");
            return (Criteria) this;
        }

        public Criteria andCronexpressionGreaterThan(String value) {
            addCriterion("cronExpression >", value, "cronexpression");
            return (Criteria) this;
        }

        public Criteria andCronexpressionGreaterThanOrEqualTo(String value) {
            addCriterion("cronExpression >=", value, "cronexpression");
            return (Criteria) this;
        }

        public Criteria andCronexpressionLessThan(String value) {
            addCriterion("cronExpression <", value, "cronexpression");
            return (Criteria) this;
        }

        public Criteria andCronexpressionLessThanOrEqualTo(String value) {
            addCriterion("cronExpression <=", value, "cronexpression");
            return (Criteria) this;
        }

        public Criteria andCronexpressionLike(String value) {
            addCriterion("cronExpression like", value, "cronexpression");
            return (Criteria) this;
        }

        public Criteria andCronexpressionNotLike(String value) {
            addCriterion("cronExpression not like", value, "cronexpression");
            return (Criteria) this;
        }

        public Criteria andCronexpressionIn(List<String> values) {
            addCriterion("cronExpression in", values, "cronexpression");
            return (Criteria) this;
        }

        public Criteria andCronexpressionNotIn(List<String> values) {
            addCriterion("cronExpression not in", values, "cronexpression");
            return (Criteria) this;
        }

        public Criteria andCronexpressionBetween(String value1, String value2) {
            addCriterion("cronExpression between", value1, value2, "cronexpression");
            return (Criteria) this;
        }

        public Criteria andCronexpressionNotBetween(String value1, String value2) {
            addCriterion("cronExpression not between", value1, value2, "cronexpression");
            return (Criteria) this;
        }

        public Criteria andJobstatusIsNull() {
            addCriterion("jobStatus is null");
            return (Criteria) this;
        }

        public Criteria andJobstatusIsNotNull() {
            addCriterion("jobStatus is not null");
            return (Criteria) this;
        }

        public Criteria andJobstatusEqualTo(String value) {
            addCriterion("jobStatus =", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusNotEqualTo(String value) {
            addCriterion("jobStatus <>", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusGreaterThan(String value) {
            addCriterion("jobStatus >", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusGreaterThanOrEqualTo(String value) {
            addCriterion("jobStatus >=", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusLessThan(String value) {
            addCriterion("jobStatus <", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusLessThanOrEqualTo(String value) {
            addCriterion("jobStatus <=", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusLike(String value) {
            addCriterion("jobStatus like", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusNotLike(String value) {
            addCriterion("jobStatus not like", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusIn(List<String> values) {
            addCriterion("jobStatus in", values, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusNotIn(List<String> values) {
            addCriterion("jobStatus not in", values, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusBetween(String value1, String value2) {
            addCriterion("jobStatus between", value1, value2, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusNotBetween(String value1, String value2) {
            addCriterion("jobStatus not between", value1, value2, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobdescriptionIsNull() {
            addCriterion("jobDescription is null");
            return (Criteria) this;
        }

        public Criteria andJobdescriptionIsNotNull() {
            addCriterion("jobDescription is not null");
            return (Criteria) this;
        }

        public Criteria andJobdescriptionEqualTo(String value) {
            addCriterion("jobDescription =", value, "jobdescription");
            return (Criteria) this;
        }

        public Criteria andJobdescriptionNotEqualTo(String value) {
            addCriterion("jobDescription <>", value, "jobdescription");
            return (Criteria) this;
        }

        public Criteria andJobdescriptionGreaterThan(String value) {
            addCriterion("jobDescription >", value, "jobdescription");
            return (Criteria) this;
        }

        public Criteria andJobdescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("jobDescription >=", value, "jobdescription");
            return (Criteria) this;
        }

        public Criteria andJobdescriptionLessThan(String value) {
            addCriterion("jobDescription <", value, "jobdescription");
            return (Criteria) this;
        }

        public Criteria andJobdescriptionLessThanOrEqualTo(String value) {
            addCriterion("jobDescription <=", value, "jobdescription");
            return (Criteria) this;
        }

        public Criteria andJobdescriptionLike(String value) {
            addCriterion("jobDescription like", value, "jobdescription");
            return (Criteria) this;
        }

        public Criteria andJobdescriptionNotLike(String value) {
            addCriterion("jobDescription not like", value, "jobdescription");
            return (Criteria) this;
        }

        public Criteria andJobdescriptionIn(List<String> values) {
            addCriterion("jobDescription in", values, "jobdescription");
            return (Criteria) this;
        }

        public Criteria andJobdescriptionNotIn(List<String> values) {
            addCriterion("jobDescription not in", values, "jobdescription");
            return (Criteria) this;
        }

        public Criteria andJobdescriptionBetween(String value1, String value2) {
            addCriterion("jobDescription between", value1, value2, "jobdescription");
            return (Criteria) this;
        }

        public Criteria andJobdescriptionNotBetween(String value1, String value2) {
            addCriterion("jobDescription not between", value1, value2, "jobdescription");
            return (Criteria) this;
        }

        public Criteria andJobclassnameIsNull() {
            addCriterion("jobClassName is null");
            return (Criteria) this;
        }

        public Criteria andJobclassnameIsNotNull() {
            addCriterion("jobClassName is not null");
            return (Criteria) this;
        }

        public Criteria andJobclassnameEqualTo(String value) {
            addCriterion("jobClassName =", value, "jobclassname");
            return (Criteria) this;
        }

        public Criteria andJobclassnameNotEqualTo(String value) {
            addCriterion("jobClassName <>", value, "jobclassname");
            return (Criteria) this;
        }

        public Criteria andJobclassnameGreaterThan(String value) {
            addCriterion("jobClassName >", value, "jobclassname");
            return (Criteria) this;
        }

        public Criteria andJobclassnameGreaterThanOrEqualTo(String value) {
            addCriterion("jobClassName >=", value, "jobclassname");
            return (Criteria) this;
        }

        public Criteria andJobclassnameLessThan(String value) {
            addCriterion("jobClassName <", value, "jobclassname");
            return (Criteria) this;
        }

        public Criteria andJobclassnameLessThanOrEqualTo(String value) {
            addCriterion("jobClassName <=", value, "jobclassname");
            return (Criteria) this;
        }

        public Criteria andJobclassnameLike(String value) {
            addCriterion("jobClassName like", value, "jobclassname");
            return (Criteria) this;
        }

        public Criteria andJobclassnameNotLike(String value) {
            addCriterion("jobClassName not like", value, "jobclassname");
            return (Criteria) this;
        }

        public Criteria andJobclassnameIn(List<String> values) {
            addCriterion("jobClassName in", values, "jobclassname");
            return (Criteria) this;
        }

        public Criteria andJobclassnameNotIn(List<String> values) {
            addCriterion("jobClassName not in", values, "jobclassname");
            return (Criteria) this;
        }

        public Criteria andJobclassnameBetween(String value1, String value2) {
            addCriterion("jobClassName between", value1, value2, "jobclassname");
            return (Criteria) this;
        }

        public Criteria andJobclassnameNotBetween(String value1, String value2) {
            addCriterion("jobClassName not between", value1, value2, "jobclassname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedulejob
     *
     * @mbg.generated do_not_delete_during_merge Mon May 06 15:51:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}