package com.ysc.entity;

public class Schedulejob {
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedulejob.jobId
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    private Integer jobid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedulejob.jobName
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    private String jobname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedulejob.jobGroup
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    private String jobgroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedulejob.cronExpression
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    private String cronexpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedulejob.jobStatus
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    private String jobstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedulejob.jobDescription
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    private String jobdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedulejob.jobClassName
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    private String jobclassname;

	public Integer getJobid() {
		return jobid;
	}

	public void setJobid(Integer jobid) {
		this.jobid = jobid;
	}

	public String getJobname() {
		return jobname;
	}

	public void setJobname(String jobname) {
		this.jobname = jobname;
	}

	public String getJobgroup() {
		return jobgroup;
	}

	public void setJobgroup(String jobgroup) {
		this.jobgroup = jobgroup;
	}

	public String getCronexpression() {
		return cronexpression;
	}

	public void setCronexpression(String cronexpression) {
		this.cronexpression = cronexpression;
	}

	public String getJobstatus() {
		return jobstatus;
	}

	public void setJobstatus(String jobstatus) {
		this.jobstatus = jobstatus;
	}

	public String getJobdescription() {
		return jobdescription;
	}

	public void setJobdescription(String jobdescription) {
		this.jobdescription = jobdescription;
	}

	public String getJobclassname() {
		return jobclassname;
	}

	public void setJobclassname(String jobclassname) {
		this.jobclassname = jobclassname;
	}

	@Override
	public String toString() {
		return "Schedulejob [jobid=" + jobid + ", jobname=" + jobname + ", jobgroup=" + jobgroup + ", cronexpression="
				+ cronexpression + ", jobstatus=" + jobstatus + ", jobdescription=" + jobdescription + ", jobclassname="
				+ jobclassname + "]";
	}


    

}