package com.ysc.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Comment {
	
	class ListNode {
		int val;
		 ListNode next;
		 ListNode(int x) { val = x; }
		@Override
		public String toString() {
			return "ListNode [val=" + val + ", next=" + next + "]";
		}
		 
		 
	}
	
	public ListNode aaa(ListNode l1, ListNode l2) {
		ListNode ll = null;
        List<Integer> list = new ArrayList<Integer>();
        while(l1 != null) {
        	int a = l1.val;
        	int b = l2.val;
            list.add( a+ b);
            
            
            l1 = l1.next;
            l2 = l2.next;
        }
        ListNode a2 = null;
        ListNode a3 = null;
        
        
        
        for ( int i=0;i<list.size();i++) {

            
            if (i==1) {
                ll = new ListNode(list.get(list.size() - 1));
            } else if ( i==2 ) {
                a2 = new ListNode(list.get(list.size() - 1));
                
            } else {
                a3 = new ListNode(list.get(list.size() - 1));
                
            }
            
        }
        ll.next = a2;
            a2.next = a3;
        return ll;
	}
	public static void main(String[] args) {
		ListNode l1 = new Comment().new ListNode(2);
		l1.next = new Comment().new ListNode(4); 
		l1.next.next =  new Comment().new ListNode(3);
		ListNode l2 = new Comment().new ListNode(5);
		l2.next = new Comment().new ListNode(6); 
		l2.next.next =  new Comment().new ListNode(4);
		new Comment().aaa(l1,l2);
	}
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Tue Apr 09 16:58:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parent
     *
     * @mbg.generated Tue Apr 09 16:58:50 CST 2019
     */
    private Integer parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.name
     *
     * @mbg.generated Tue Apr 09 16:58:50 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.text
     *
     * @mbg.generated Tue Apr 09 16:58:50 CST 2019
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.time
     *
     * @mbg.generated Tue Apr 09 16:58:50 CST 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Tue Apr 09 16:58:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Tue Apr 09 16:58:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parent
     *
     * @return the value of comment.parent
     *
     * @mbg.generated Tue Apr 09 16:58:50 CST 2019
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parent
     *
     * @param parent the value for comment.parent
     *
     * @mbg.generated Tue Apr 09 16:58:50 CST 2019
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.name
     *
     * @return the value of comment.name
     *
     * @mbg.generated Tue Apr 09 16:58:50 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.name
     *
     * @param name the value for comment.name
     *
     * @mbg.generated Tue Apr 09 16:58:50 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.text
     *
     * @return the value of comment.text
     *
     * @mbg.generated Tue Apr 09 16:58:50 CST 2019
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.text
     *
     * @param text the value for comment.text
     *
     * @mbg.generated Tue Apr 09 16:58:50 CST 2019
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.time
     *
     * @return the value of comment.time
     *
     * @mbg.generated Tue Apr 09 16:58:50 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.time
     *
     * @param time the value for comment.time
     *
     * @mbg.generated Tue Apr 09 16:58:50 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}