package com.ysc.entity;

import java.util.Date;

public class PeopleFlow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people_flow.id
     *
     * @mbg.generated Mon Apr 08 14:30:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people_flow.count
     *
     * @mbg.generated Mon Apr 08 14:30:57 CST 2019
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people_flow.date
     *
     * @mbg.generated Mon Apr 08 14:30:57 CST 2019
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people_flow.id
     *
     * @return the value of people_flow.id
     *
     * @mbg.generated Mon Apr 08 14:30:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people_flow.id
     *
     * @param id the value for people_flow.id
     *
     * @mbg.generated Mon Apr 08 14:30:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people_flow.count
     *
     * @return the value of people_flow.count
     *
     * @mbg.generated Mon Apr 08 14:30:57 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people_flow.count
     *
     * @param count the value for people_flow.count
     *
     * @mbg.generated Mon Apr 08 14:30:57 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people_flow.date
     *
     * @return the value of people_flow.date
     *
     * @mbg.generated Mon Apr 08 14:30:57 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people_flow.date
     *
     * @param date the value for people_flow.date
     *
     * @mbg.generated Mon Apr 08 14:30:57 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

	@Override
	public String toString() {
		return "PeopleFlow [id=" + id + ", count=" + count + ", date=" + date + "]";
	}
    
}