package com.ysc.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ysc.entity.Schedulejob;
import com.ysc.entity.SchedulejobExample;

public interface SchedulejobMapper {
	void deleteByNameGroup(Schedulejob job);
	
	void updateByNameGroup(Schedulejob record);
	
	
	List<Schedulejob> getJobByCondition(Schedulejob job);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    long countByExample(SchedulejobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    int deleteByExample(SchedulejobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    int deleteByPrimaryKey(Integer jobid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    int insert(Schedulejob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    int insertSelective(Schedulejob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    List<Schedulejob> selectByExample(SchedulejobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    Schedulejob selectByPrimaryKey(Integer jobid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") Schedulejob record, @Param("example") SchedulejobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    int updateByExample(@Param("record") Schedulejob record, @Param("example") SchedulejobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    int updateByPrimaryKeySelective(Schedulejob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedulejob
     *
     * @mbg.generated Mon May 06 15:51:00 CST 2019
     */
    int updateByPrimaryKey(Schedulejob record);
}